version: 2.1
jobs:
  build:
    docker:
      - image: kavithareddy/terra:nodejs
    steps: 
      - checkout 
      - run:  | 
         cat main.tf
         terraform init 
         terraform 0.13upgrade --yes 
         terraform plan 
         terraform apply -auto-approve 