version: 2.1
jobs:
  build:
    docker:
      - image: kavithareddy/terraform-heroku:latest
    steps: 
      - checkout 
      - run:  | 
         pwd
         ls
         terraform init 
         terraform plan 
         terraform apply -auto-approve 