version: 2.1
jobs:
  build:
    docker:
      - image: kavithareddy/terra:nodejs
    steps: 
      - checkout 
      - run:  | 
         ls
         pwd
         cd ../
         ls
         cd terraform/
         cat main.tf
         pwd
         terraform 0.13upgrade .
         terraform init 
         terraform 0.13upgrade --yes 
         terraform plan 
         terraform apply -auto-approve 